version: "3.7"

services:
  airflow-web:
    image: hugopascual/airflow-bdfi
    container_name: airflow-web
    ports:
      - "3000:8080"
    command: airflow webserver --port 8080
    environment:
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    networks:
      - predictions_net

  airflow-scheduler:
    image: hugopascual/airflow-bdfi
    container_name: airflow-scheduler
    command: airflow scheduler
    networks:
      - predictions_net
    restart: always

networks:
  predictions_net:
    name: predictions_net
    driver: bridge